"""added now_time

Revision ID: 9fbab25c7b30
Revises: d0b37faaaeee
Create Date: 2018-08-15 12:47:44.907001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbab25c7b30'
down_revision = 'd0b37faaaeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('itemtime', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'itemtime')
    # ### end Alembic commands ###
