"""first migrate

Revision ID: d0b37faaaeee
Revises: 
Create Date: 2018-08-07 21:30:22.845744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b37faaaeee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_itemname'), 'item', ['itemname'], unique=True)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('shop', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=400), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('reviews_num', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=400), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_index(op.f('ix_item_itemname'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
